version: "3.8"

services:
  app:
    build: .
    container_name: app
    hostname: app
    restart: always
    ports:
      - "80:80"
    networks:
      - twotier
    volumes:
      - .:/var/www/html
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: dbuser
      DB_PASSWORD: redhat
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: redhat
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: redhat
    networks:
      - twotier
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

networks:
  twotier:

